### ISSUE TITLE
Fix the Rust Toolchain Version

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/rust-lib#1]
### Summary
Due to some issues with rustc nightlies, we're currently stuck compiling these libraries only with `nightly-2019-11-04`. This is not a place we want to be stuck forever, so at some point we need to take the time to upgrade to a newer nightly.

This issue also applies to the rust code in [enso](https://github.com/enso-org/enso).

### Value
We won't be stuck on an old rust toolchain any longer.

### Specification

- [ ] Wait for the IDE team to update their rust toolchain.
- [ ] Update the usable rust toolchain in this library, and stay up to date with nightlies.

### Acceptance Criteria & Test Cases

- We can use `nightly`, rather than a specific pinned nightly.

**Comment by mwu-tow** [comment]
Fixed by #32
